aspire:  
      
  jbehave:
    metat-data:
    thread: 1
    story-time-out: 3000 
    rerun: 0
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include:
#          - stories/desktop_web/**/**.story
#          - stories/mobile_web/**/**.story
###          - stories/mobile_web/harrods/**.story
###          - stories/mobile_web/barneys/**.story


          - stories/mobile_web/landsend/**.story
          - stories/mobile_web/lanedbryant/**.story          
          - stories/mobile_web/neimanmarcus/**.story
          - stories/mobile_web/bcbg/**.story
          - stories/mobile_web/eddiebauer/**.story
          - stories/mobile_web/lordandtaylor/**.story 
          - stories/mobile_web/saksoff/**.story 
          - stories/mobile_web/nordstrom/**.story
          - stories/mobile_web/pacsun/**.story
          - stories/mobile_web/bergdorf/**.story
          - stories/mobile_web/saks/**.story
          - stories/mobile_web/ruelala/**.story
          - stories/mobile_web/llbean/**.story
          - stories/mobile_web/partycitycanada/**.story
          - stories/mobile_web/ebags/**.story
          - stories/mobile_web/lastcall/**.story
          - stories/mobile_web/gap/**.story
          - stories/mobile_web/underarmour/**.story
          


  webdriver:
    scope: restart
    strategy: MIXED
    default-driver-name: android
    android:
      name: android
      enabled: true
      run-on: physical-device
      remote:
       enabled: false
       user: jnassar
       key: 93b9389d-4700-49f4-98fd-dd460a5c750b
       use-last-modified-file: false
       upload-file: false
       url: http://jnassar:93b9389d-4700-49f4-98fd-dd460a5c750b@ondemand.saucelabs.com:80/wd/hub
       type: saucelab
      capabilities:
        platformName: Android
        platformVersion: 8.0
        deviceName: Samsung Galaxy S7 Edge GoogleAPI Emulator
        fullReset: false
        autoGrantPermissions: true
        autoAcceptAlerts: true
        browserName: Chrome 
        appiumVersion: 1.8.1
        timeoutInSeconds: 6000
        maxDuration: 1800
        newCommandTimeout: 60000
        timeout-in-seconds: 1800
        
        
  mobile:
    appium:
      localservice:
        strategy: fixed-provided
        connected-device-command: C:\Users\aziyadeh\AppData\Local\Android\Sdk\platform-tools\adb.exe
        auto-lunch: true
        node-path: C:\Program Files\nodejs\node.exe
        appium-j-s-file-path: C:\Users\aziyadeh\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
        windows-kill-node-command: taskkill \f \im node.exe  
           
  screenshot:
    enabled: true
    only-on-failure: true
    filesaver:
      enabled: true
      folder-location: ./screenshots/
spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: ERROR
  file: application_zurqan.log  


endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  env:
    sensitive: false
    
    
server:
  port: 0







   