aspire:  
  jbehave:
    metat-data:
    - -s2 
    thread: 2
    story-time-out: 3000 
    rerun: 0
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include: 
        - stories/**/**login-001.story
        - stories/**/TC-Deal_Center-006_2.story
        - stories/**/**/TC-Roles-001.story
         

        
        
  screenshot:
    enabled: true
    filesaver:
      enabled: true
      folder-location: C:\Users\Nalsouqi\Pictures\screenshots\

spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: DEBUG
  file: application_zurqan.log  


endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  env:
    sensitive: false
    
    
server:
  port: 0



      



   