aspire:  
      
  jbehave:
    metat-data:
    thread: 1
    story-time-out: 3000 
    rerun: 0
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include: 
          - stories/bcbg/**.story
          - stories/eddiebauer/**.story
          - stories/bergdorf/**.story
          - stories/ebags/**.story
          - stories/williamssonoma/**.story
          - stories/eddiebauer/**.story
          - stories/george/**.story
          - stories/herroom/**.story
          - stories/hisroom/**.story
          - stories/lastcall/**.story
          - stories/llbean/**.story
          - stories/lordandtaylor/**.story 
          - stories/neimanmarcus/**.story
          - stories/nordstrom/**.story
          - stories/pacsun/**.story
          - stories/partycitycanada/**.story
          - stories/ruelala/**.story
          - stories/saks/**.story
          - stories/saksoff/**.story
          - stories/underarmour/**.story
          - stories/williamssonoma/**.story
          - stories/potterybarn/**.story
#          - stories/sephora/**.story
#          - stories/lanebryant/**.story
#          - stories/landsend/**.story
#          - stories/harrods/**.story
#          - stories/gilt/**.story
#          - stories/generalpants/**.story
#          - stories/barneys/**.story
#          - stories/gap/*.story
          
  webdriver:
    strategy: mixed
    scope: scenario
    default-driver-name: firefox
    android:
      name: android
      enabled: false
      run-on: virtual-device
      remote:
       enabled: true
       user: jnassar
       key: 93b9389d-4700-49f4-98fd-dd460a5c750b
       use-last-modified-file: false
       upload-file: false
       url: http://jnassar:93b9389d-4700-49f4-98fd-dd460a5c750b@ondemand.saucelabs.com:80/wd/hub
       type: saucelab
      capabilities:
        platformName: Android
        platformVersion: 7.1
        deviceName: Samsung Galaxy S7 Edge GoogleAPI Emulator
        fullReset: false
        deviceOrientation: portrait
        autoGrantPermissions: true
        browserName: Chrome
        appiumVersion: 1.7.2
        
        
  mobile:
    appium:
      localservice:
        strategy: fixed-provided
        number-of-services: 1
        kill-all-node-services-before-start: true        
           
  screenshot:
    enabled: true
    only-on-failure: true
    filesaver:
      enabled: true
      folder-location: ./screenshots/
spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: ERROR
  file: application_zurqan.log  


endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  env:
    sensitive: false
    
    
server:
  port: 0







   